### ISSUE TITLE
Nice addon, but...

### ISSUE THREAD

**Issue by LokeYourC3PH** [Chronomly/firefox-discord#2]
Like I would want to add this for fun just like with the Minecraft Mod, however, I can honestly say that I am a bit too lazy to "download a repository and compile" myself because I have stopped programming for a while now (sorry). It would be really great if you could start making releases of this pre-compiled.

Regards, Loke

**Comment by Chrono-byte** [comment]
It's not done yet, will make the add-on portion available on Firefox add-ons website, and will make an exe available on my website

**Comment by oatmealine** [comment]
i really want you to finish this because this got me really excited when i first found it

**Comment by Chrono-byte** [comment]
It's working now

I'm waiting on my friend to get an EXE version available.
