### ISSUE TITLE
How to install ?

### ISSUE THREAD

**Issue by siffreinsg** [Chronomly/firefox-discord#3]
I don't understand how to install the extension, can you help me ?

**Comment by PoorPocketsMcNewHold** [comment]
According to the wiki, This extension is not finished. _Due to the "later:tm:"_
In theory, I'm gonna say that you will need to git that repository somewhere on your PC (or manually download it for the moment), and then. Install all of those .json & .js files using the npm install command.
However, It does seems that it need to extra dependencies.

**Comment by Chrono-byte** [comment]
It's working now.
I know that I'm 2 years late on this but at least it's done now.
